### ISSUE TITLE
Docker image does not work with non privileged user parameter

### ISSUE THREAD

**Issue by portiid** [smokin-salmon/smoked-salmon#47]
When --user=uid:gid parameter is passed to docker, there is an error occur:
```
error: failed to create directory `/.cache/uv`: Permission denied (os error 13)
```
Usually it's connected to folder permissions after cloning of github repo.

**Comment by portiid** [comment]
> Let's say I manually make that directory, my next error is:
> 
> error: failed to open file `/.cache/uv/CACHEDIR.TAG`: Permission denied (os error 13)

Yes, that is correct. It is not about the directory itself (even if you mount it from outside as a volume it won't work. It's because /app folder is inaccessible by whatever UID you're trying to access it. It should be either chown-ed to that UID or made all+rx

**Comment by redusys** [comment]
Thank you for the report. I have a simple idea for a fix (+rx for all as you said, in the docker image), but I need to wrap up a few other things first. I'll get to it soon.

**Comment by redusys** [comment]
Could you confirm this is fixed in 0.9.3 please?

**Comment by portiid** [comment]
```
# docker run --rm -it --user=1026:100 ..........   ghcr.io/smokin-salmon/smoked-salmon:latest checkconf
The database needs updating. Please run `salmon migrate`.

Traceback (most recent call last):
  File "/app/.venv/bin/salmon", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/run.py", line 14, in main
    show_release_notification()
  File "/app/salmon/release_notification.py", line 76, in show_release_notification
    local_version = _get_local_version(LOCAL_VERSION_FILE)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/salmon/release_notification.py", line 34, in _get_local_version
    with open(version_file, encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/app/data/version.py'
```
Still not working for me out of the box. Please check permissions of " /app " when you have a chance
Maybe just do recursive for the whole folder?

**Comment by redusys** [comment]
Published 0.9.3.2 with full rights to /app , if you can test it when you get the chance

**Comment by portiid** [comment]
```
PermissionError: [Errno 13] Permission denied: '/app/data/version.py'
```

nope. same. I'm going to check what's going on later today and let you know

**Comment by redusys** [comment]
Not sure what is going on then, if you're using the last image. I added that part in the Dockerfile:
`RUN mkdir -p /.cache/uv && chmod -R 777 /.cache/uv /app`

Maybe you can enter the docker and check the permissions of /app, but it shouldn't be a permission denied.

**Comment by redusys** [comment]
Nevermind, I think it's just me being stupid... I did the chmod before copying the files into the docker image... Let me try to push another fix.

**Comment by redusys** [comment]
0.9.3.3 available to test, when you have time 🙏

**Comment by portiid** [comment]
so far so good. Thank you! Seems to be working fine now, I'll double check everything within couple days

**Comment by redusys** [comment]
Thanks

**Comment by portiid** [comment]
>   File "/app/salmon/database.py", line 24, in migrate
>     with sqlite3.connect(DB_PATH) as conn:
>          ^^^^^^^^^^^^^^^^^^^^^^^^
> sqlite3.OperationalError: unable to open database file

check permissions of ./smoked.db

**Comment by redusys** [comment]
As @portiid said, your file smoked.db (which should be outside of your container, mapped as volume), must be readable/writable by your user.

**Comment by maksii** [comment]
Not sure why these issues were closed, when the original problems with smoked.db were not resolved.

The problem is not in permissions, access, or the user. Mapping specifically requires an actual file to exist(e.g., like config.py), and depending on the system where Docker is running, it may be pre-created as an actual path(folder), making progress impossible.

The actual resolution should be to be able to map just the app folder, not specific files. Let the script pick up the config and create the DB.

As a workaround, precreate sqlite and place it under volume mapping
`python -c "import sqlite3; sqlite3.connect('smoked.db').close()"`
